
version: '2.0'
services:
  nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /root/dapp-store/nginx/ssl:/etc/nginx/certs
      - ./my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
    environment:
      - DEFAULT_HOST=www.dapp.com
      - CERT_NAME=server
    restart: always
