version: "2.0"
services:
  nginx:
    build: ./nginx
    ports:
      - "8082:80"
    links:
      - backend
    environment:
      - VIRTUAL_HOST=site2.com
    networks:
      - default
      - nginx_proxy_default
  backend:
    build: ./backend
    volumes:
      - ./backend:/opt/workspace
networks:
  nginx_proxy_default:
    external: true
